import SwiftUI

struct TermsAndConditionsView: View {
    @Environment(\.dismiss) var dismiss
    @Binding var agreedToTerms: Bool
    
    var body: some View {
        VStack(spacing: 0) {
            // Header
            VStack(spacing: 8) {
                RoundedRectangle(cornerRadius: 3)
                    .fill(Color(uiColor: .systemGray4))
                    .frame(width: 40, height: 6)
                    .padding(.top, 12)
                
                Text("Terms & Conditions")
                    .font(.title2.bold())
                    .padding(.top, 8)
                
                Text("Please read these terms carefully before creating an account with AstraFi.")
                    .font(.system(size: 14))
                    .foregroundColor(Color(uiColor: .secondaryLabel))
                    .multilineTextAlignment(.center)
                    .padding(.horizontal)
                    .padding(.bottom, 16)
            }
            .background(Color(uiColor: .systemGroupedBackground))
            
            Divider()
            
            // Content
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    
                    TermsSectionView(
                        icon: "doc.text.magnifyingglass",
                        iconColor: .blue,
                        title: "1. Acceptance of Terms",
                        content: "By creating an account, you agree to these Terms and Conditions. AstraFi is a personal finance tool designed to help you track your net worth, goals, investments, and financial health."
                    )
                    
                    TermsSectionView(
                        icon: "lock.shield",
                        iconColor: .green,
                        title: "2. Data Privacy & Setu Integration",
                        content: "AstraFi uses Setu (an RBI-approved Account Aggregator) to securely fetch your financial data. Your data is encrypted end-to-end and is used strictly to provide you with personalized financial insights. We will never sell your personal or financial data to third parties."
                    )
                    
                    TermsSectionView(
                        icon: "exclamationmark.triangle",
                        iconColor: .orange,
                        title: "3. Not Professional Advice",
                        content: "The insights, financial health scores, and investment summaries provided by AstraFi are generated by algorithms. They are for informational purposes only and do not constitute certified professional financial, investment, or tax advice. Always consult a qualified professional before making major financial decisions."
                    )
                    
                    TermsSectionView(
                        icon: "person.text.rectangle",
                        iconColor: .purple,
                        title: "4. User Responsibilities",
                        content: "You are responsible for maintaining the confidentiality of your login credentials. AstraFi is not liable for inaccuracies resulting from manually entered data or unverified third-party syncs."
                    )
                    
                    TermsSectionView(
                        icon: "building.columns",
                        iconColor: .red,
                        title: "5. Governing Law & Jurisdiction",
                        content: "These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising in connection with AstraFi shall be subject to the exclusive jurisdiction of the competent courts in Meerut, Uttar Pradesh, India."
                    )
                    
                }
                .padding(24)
            }
            .background(Color(uiColor: .systemBackground))
            
            Divider()
            
            // Sticky Bottom Bar
            VStack {
                AuthPrimaryButton(title: "I Agree & Continue") {
                    agreedToTerms = true
                    dismiss()
                }
                .padding(.horizontal, 24)
                .padding(.vertical, 16)
            }
            .background(Color(uiColor: .systemGroupedBackground))
        }
    }
}

struct TermsSectionView: View {
    let icon: String
    let iconColor: Color
    let title: String
    let content: String
    
    var body: some View {
        HStack(alignment: .top, spacing: 16) {
            Image(systemName: icon)
                .font(.system(size: 24))
                .foregroundColor(iconColor)
                .frame(width: 32)
            
            VStack(alignment: .leading, spacing: 6) {
                Text(title)
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundColor(.primary)
                
                Text(content)
                    .font(.system(size: 14))
                    .foregroundColor(Color(uiColor: .secondaryLabel))
                    .lineSpacing(4)
            }
        }
    }
}

// Helper extension for hex colors if not already present

